<?php

namespace Database\Seeders;

use App\Models\Ticket;
use Illuminate\Database\Seeder;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        $tickets = [
            [
                'ticket_id' => 'OZJ-20260310-DEMO1',
                'ringkasan_sinyal' => 'Potensi keterlambatan distribusi bantuan',
                'judul_sinyal' => 'Keterlambatan Logistik Program A',
                'deskripsi_sinyal' => 'Laporan menunjukkan distribusi logistik terlambat 3 hari di wilayah X',
                'level_sinyal' => 'Meso',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Logistik',
                'nama_program' => 'Program Bantuan Pangan',
                'nama_pelapor' => 'Budi Santoso',
                'nama_lokasi' => 'Kabupaten Sleman',
                'risiko_teridentifikasi' => 'Distribusi tidak merata',
                'rekomendasi_ai' => 'Percepat koordinasi dengan gudang regional',
                'jenis_sumber' => 'Laporan Lapangan',
                'waktu_catat' => '2026-03-10 10:30:00',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'Tinggi',
                'skor_urgensi_hukum' => 72,
                'skor_urgensi_tertinggi' => 72,
            ],
            [
                'ticket_id' => 'OZJ-20260310-4535',
                'ringkasan_sinyal' => 'Observasi ini menyoroti tantangan dalam penyediaan bantuan anak yang tepat waktu di tingkat regional',
                'judul_sinyal' => 'Keterlambatan Akses Jeugdhulp',
                'deskripsi_sinyal' => 'Terdapat indikasi kuat bahwa anak-anak di wilayah ini mengalami penundaan signifikan dalam menerima layanan bantuan anak (jeugdhulp).',
                'level_sinyal' => 'Meso',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Akses Layanan',
                'nama_pelapor' => 'Anonim',
                'risiko_teridentifikasi' => 'Peningkatan kasus kekerasan dan penelantaran anak yang tidak tertangani.; Dampak negatif jangka panjang pada perkembangan dan kesejahteraan anak.',
                'rekomendasi_ai' => 'Segera lakukan audit mendalam terhadap alur kerja dan kapasitas penyedia jeugdhulp di tingkat regional.',
                'jenis_sumber' => 'input-manual',
                'waktu_catat' => '2026-03-10 07:57:25',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'KRITIS',
                'skor_urgensi_hukum' => 95,
                'dasar_hukum' => 'Jeugdwet Art. 2.4',
                'skor_urgensi_tertinggi' => 95,
                'sinyal_index' => 1,
                'sinyal_total' => 4,
            ],
            [
                'ticket_id' => 'OZJ-20260310-4535-2',
                'ringkasan_sinyal' => 'Observasi ini menyoroti tantangan dalam penyediaan bantuan anak yang tepat waktu di tingkat regional',
                'judul_sinyal' => 'Potensi Pelanggaran Meldcode',
                'deskripsi_sinyal' => 'Keterlambatan dalam penyediaan jeugdhulp, terutama jika disertai dengan indikasi adanya kekerasan, penelantaran, atau situasi berbahaya lainnya, dapat memicu kewajiban profesional untuk melaporkan.',
                'level_sinyal' => 'Meso',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Pelaporan Kekerasan',
                'nama_pelapor' => 'Anonim',
                'risiko_teridentifikasi' => 'Pelanggaran hukum dan etika profesional oleh lembaga terkait.',
                'rekomendasi_ai' => 'Tinjau dan perbarui protokol internal terkait Meldcode.',
                'jenis_sumber' => 'input-manual',
                'waktu_catat' => '2026-03-10 07:57:25',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'Tinggi',
                'skor_urgensi_hukum' => 85,
                'dasar_hukum' => 'Jeugdwet Art. 4.1.1, Wet verplichte meldcode',
                'skor_urgensi_tertinggi' => 85,
                'sinyal_index' => 2,
                'sinyal_total' => 4,
            ],
            [
                'ticket_id' => 'OZJ-20260310-4535-3',
                'ringkasan_sinyal' => 'Observasi ini menyoroti tantangan dalam penyediaan bantuan anak yang tepat waktu di tingkat regional',
                'judul_sinyal' => 'Risiko Terhadap Kepentingan Terbaik Anak',
                'deskripsi_sinyal' => 'Penundaan dalam intervensi dan potensi kegagalan pelaporan secara langsung mengancam prinsip kepentingan terbaik anak (UNCRC Art. 3).',
                'level_sinyal' => 'Makro',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Perlindungan Anak',
                'nama_pelapor' => 'Anonim',
                'risiko_teridentifikasi' => 'Penurunan kepercayaan publik terhadap sistem layanan anak.',
                'rekomendasi_ai' => 'Alokasikan sumber daya tambahan (pendanaan, staf) untuk mengatasi kesenjangan kapasitas.',
                'jenis_sumber' => 'input-manual',
                'waktu_catat' => '2026-03-10 07:57:25',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'KRITIS',
                'skor_urgensi_hukum' => 98,
                'dasar_hukum' => 'UNCRC Art. 3',
                'skor_urgensi_tertinggi' => 98,
                'sinyal_index' => 3,
                'sinyal_total' => 4,
            ],
            [
                'ticket_id' => 'OZJ-20260310-4535-4',
                'ringkasan_sinyal' => 'Observasi ini menyoroti tantangan dalam penyediaan bantuan anak yang tepat waktu di tingkat regional',
                'judul_sinyal' => 'Indikasi Bahaya Akut',
                'deskripsi_sinyal' => 'Frasa acute gevaar terkait Veilig Thuis menunjukkan adanya potensi bahaya akut terhadap anak. Keterlambatan dalam penanganan sangat mengkhawatirkan.',
                'level_sinyal' => 'Mikro',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Bahaya Akut',
                'nama_pelapor' => 'Anonim',
                'risiko_teridentifikasi' => 'Potensi peningkatan kebutuhan akan intervensi yang lebih intensif dan mahal.',
                'rekomendasi_ai' => 'Perkuat mekanisme koordinasi antara gemeente, jeugdhulp-aanbieders, dan Veilig Thuis.',
                'jenis_sumber' => 'input-manual',
                'waktu_catat' => '2026-03-10 07:57:25',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'KRITIS',
                'skor_urgensi_hukum' => 100,
                'dasar_hukum' => 'Veilig Thuis (Acute gevaar)',
                'skor_urgensi_tertinggi' => 100,
                'sinyal_index' => 4,
                'sinyal_total' => 4,
            ],
            [
                'ticket_id' => 'OZJ-20260310-1221',
                'ringkasan_sinyal' => 'Seorang anak berusia 8 tahun di Rotterdam Selatan menunjukkan tanda-tanda verwaarlozing',
                'judul_sinyal' => 'Verwaarlozing pada Anak',
                'deskripsi_sinyal' => 'Anak usia 8 tahun terlihat sendiri di malam hari dan sering tidak hadir di sekolah selama 3 minggu terakhir.',
                'level_sinyal' => 'Mikro',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Verwaarlozing',
                'wa_chat_id' => '6281575817391@c.us',
                'risiko_teridentifikasi' => 'Risiko verwaarlozing fisik dan emosional yang berkelanjutan.; Potensi isolasi sosial anak.',
                'rekomendasi_ai' => 'Segera hubungi Veilig Thuis untuk penilaian risiko akut dan panduan lebih lanjut.; Aktifkan protokol Meldcode langkah 4 dan 5.',
                'jenis_sumber' => 'whatsapp',
                'waktu_catat' => '2026-03-10 08:11:00',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'Tinggi',
                'skor_urgensi_hukum' => 75,
                'dasar_hukum' => 'Jeugdwet Art. 4.1.1 (Meldcode), UNCRC Art. 3',
                'bahasa_output' => 'id',
                'nama_pengirim' => 'Stevano',
                'nomor_pengirim' => '6281575817391@c.us',
                'skor_urgensi_tertinggi' => 75,
                'sinyal_index' => 1,
                'sinyal_total' => 2,
                'rr_tenggat_waktu' => '48-72 jam',
                'rr_tindakan_utama' => 'Melakukan penilaian risiko segera terhadap keselamatan dan kesejahteraan anak.',
                'rr_pihak_yang_dihubungi' => 'Veilig Thuis, Wijkteam',
                'rr_langkah_dokumentasi' => 'Dokumentasikan semua observasi, laporan dari tetangga, dan tindakan yang diambil sesuai dengan Meldcode.',
            ],
            [
                'ticket_id' => 'OZJ-20260310-1221-2',
                'ringkasan_sinyal' => 'Seorang anak berusia 8 tahun di Rotterdam Selatan menunjukkan tanda-tanda verwaarlozing',
                'judul_sinyal' => 'Kurangnya Keterlibatan Layanan',
                'deskripsi_sinyal' => 'Keluarga belum terdaftar di wijkteam manapun, menunjukkan potensi kurangnya akses atau keterlibatan dengan layanan dukungan.',
                'level_sinyal' => 'Meso',
                'urgensi_sinyal' => 'Sedang',
                'kategori_sinyal' => 'Akses Layanan',
                'wa_chat_id' => '6281575817391@c.us',
                'risiko_teridentifikasi' => 'Keterlambatan dalam memberikan bantuan dan dukungan yang diperlukan kepada keluarga.',
                'rekomendasi_ai' => 'Koordinasikan dengan wijkteam atau layanan terkait untuk memastikan keluarga mendapatkan dukungan yang memadai.',
                'jenis_sumber' => 'whatsapp',
                'waktu_catat' => '2026-03-10 08:11:00',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'Sedang',
                'skor_urgensi_hukum' => 55,
                'dasar_hukum' => 'Jeugdwet Art. 2.4',
                'bahasa_output' => 'id',
                'nama_pengirim' => 'Stevano',
                'nomor_pengirim' => '6281575817391@c.us',
                'skor_urgensi_tertinggi' => 75,
                'sinyal_index' => 2,
                'sinyal_total' => 2,
                'rr_tenggat_waktu' => '1-2 minggu',
                'rr_tindakan_utama' => 'Berkoordinasi dengan wijkteam atau layanan terkait.',
                'rr_pihak_yang_dihubungi' => 'Wijkteam, Jeugdzorginstelling',
                'rr_langkah_dokumentasi' => 'Catat upaya untuk menghubungkan keluarga dengan layanan.',
            ],
            [
                'ticket_id' => 'OZJ-20260310-9694',
                'ringkasan_sinyal' => 'Seorang anak berusia 8 tahun di Rotterdam Selatan dilaporkan menunjukkan tanda-tanda penelantaran',
                'judul_sinyal' => 'Potensi Penelantaran Anak',
                'deskripsi_sinyal' => 'Anak usia 8 tahun sering tidak hadir di sekolah selama 3 minggu terakhir dan dilaporkan sering terlihat sendirian di malam hari.',
                'level_sinyal' => 'Mikro',
                'urgensi_sinyal' => 'Tinggi',
                'kategori_sinyal' => 'Verwaarlozing',
                'wa_chat_id' => '6281575817391@c.us',
                'risiko_teridentifikasi' => 'Risiko penelantaran anak yang berkelanjutan.; Potensi dampak negatif jangka panjang.',
                'rekomendasi_ai' => 'Segera hubungi Veilig Thuis untuk melaporkan kekhawatiran.; Lakukan penilaian risiko komprehensif.',
                'jenis_sumber' => 'whatsapp',
                'waktu_catat' => '2026-03-10 09:28:17',
                'status_ticket' => 'Open',
                'status_eskalasi' => 'Tinggi',
                'skor_urgensi_hukum' => 75,
                'dasar_hukum' => 'Jeugdwet Art. 4.1.1, Wet verplichte meldcode',
                'bahasa_output' => 'id',
                'nama_pengirim' => 'Stevano',
                'nomor_pengirim' => '6281575817391@c.us',
                'skor_urgensi_tertinggi' => 75,
                'sinyal_index' => 1,
                'sinyal_total' => 2,
                'rr_tenggat_waktu' => '48-72 jam',
                'rr_tindakan_utama' => 'Mulai proses Meldcode (langkah 4-5), lakukan penilaian risiko awal.',
                'rr_pihak_yang_dihubungi' => 'Veilig Thuis',
                'rr_langkah_dokumentasi' => 'Dokumentasikan semua observasi, laporan tetangga, dan tindakan yang diambil.',
            ],
        ];

        foreach ($tickets as $ticketData) {
            Ticket::create($ticketData);
        }
    }
}
